#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <run_config>"
    echo "Example: $0 ./auto_profile/test_configs/run_deepseek_r1_nvfp4.json"
    exit 1
fi

source "$(dirname "$0")/env.sh"

run_config="$1"
output_dir=$(python -c "from common.utils import output_dir_from_run_config; print(output_dir_from_run_config('${run_config}'))")
test_results_dir="${output_dir}/test_results"

echo "========================================"
echo "  AI Auto Performance Analysis Pipeline"
echo "========================================"
echo "  Run config:    ${run_config}"
echo "  Output dir:    ${output_dir}"
echo "  Test results:  ${test_results_dir}"
echo "========================================"

# Step 1: Run benchmarks and profiling across frameworks (vllm, sgl, trt)
echo ""
echo "=== STEP 1: Run benchmarks and profiling ==="
./auto_profile/run_profile_core.sh "${run_config}"

# Step 2: Parse results, generate summary tables, and generate per-test-case analysis configs
echo ""
echo "=== STEP 2: Parse results and generate analysis configs ==="
python -m auto_profile.run_profile_summary \
    --run-config "${run_config}" \
    --override-output-dir

# Step 3: For each test case where configs were generated, run the analysis pipeline
echo ""
echo "=== STEP 3: Run analysis pipeline ==="

if [ ! -d "${test_results_dir}" ]; then
    echo "No test_results directory found at ${test_results_dir}"
    exit 0
fi

# Find all test_id_with_batch directories that have analysis configs
for test_dir in "${test_results_dir}"/*/; do
    test_dir="${test_dir%/}"  # remove trailing slash
    test_name="$(basename "${test_dir}")"

    # Check if this test case has single trace configs (generated by step 2)
    single_configs=( "${test_dir}"/single_trace_config_*.json )
    if [ ! -f "${single_configs[0]}" ]; then
        continue
    fi

    cross_config="${test_dir}/cross_trace_config.json"
    if [ ! -f "${cross_config}" ]; then
        echo "SKIP ${test_name}: no cross_trace_config.json"
        continue
    fi

    echo ""
    echo "========================================"
    echo "  Analyzing: ${test_name}"
    echo "========================================"

    # 3a: Run single-trace analysis for each framework
    for st_config in "${single_configs[@]}"; do
        fw_name="$(basename "${st_config}" .json | sed 's/single_trace_config_//')"
        echo ""
        echo "--- Single-trace analysis: ${fw_name} ---"
        python -m auto_analyze.run_single_trace \
            --config "${st_config}"
    done

    # 3b: Run cross-trace analysis
    echo ""
    echo "--- Cross-trace analysis ---"
    python -m auto_analyze.run_cross_trace \
        --config "${cross_config}" \
        --clean

    # Extract the cross-trace output directory from the config
    cross_output_dir=$(python -c "import json; print(json.load(open('${cross_config}'))['output_dir'])")

    echo ""
    echo "  Cross-trace results: ${cross_output_dir}"

    # 3c: Generate summary PDF report
    echo ""
    echo "--- Summary PDF ---"
    python -m auto_analyze.run_summary_pdf \
        --cross-config "${cross_config}"

    # 3d: Build combined trace visualization
    echo ""
    echo "--- Cross trace JSON ---"
    python -m auto_analyze.run_chrome_trace \
        --cross-config "${cross_config}"

    # 3e: Create JIRA tasks for identified issues
    echo ""
    echo "--- Create JIRA tasks ---"
    python -m auto_analyze.run_jiras \
        --cross-config "${cross_config}"
done

echo ""
echo "========================================"
echo "  Pipeline complete"
echo "========================================"
