"""Prompt classes for the Phase 0-5 bug-fix porting pipeline."""
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar

from auto_bug_fix.bug_fix_config import BugFixConfig
from common.claude_utils import ClaudeConfig


def create_context_str(claude_config: ClaudeConfig, config: BugFixConfig) -> str:
    return (
        "<context>\n"
        f"<repo_path>{config.repo_path}</repo_path>\n"
        f"<build_dir>{config.build_dir}</build_dir>\n"
        f"<source_branch>{config.source_branch}</source_branch>\n"
        f"<target_branch>{config.target_branch}</target_branch>\n"
        f"<source_fix_commit>{config.source_fix_commit}</source_fix_commit>\n"
        f"<bug_description>{config.bug_description}</bug_description>\n"
        f"<issue_id>{config.issue_id}</issue_id>\n"
        f"<build_command>{config.build_command}</build_command>\n"
        f"<test_command>{config.test_command}</test_command>\n"
        f"<cwd>{claude_config.cwd}</cwd>\n"
        "</context>\n"
    )


SEMANTIC_TRIAGE_FILE = "semantic_triage.json"


@dataclass
class SemanticTriagePrompt:
    """Prompt for Phase 0.5 — LLM-powered semantic analysis of the commit before cherry-pick."""
    context: str
    fix_diff: str
    source_branch: str
    target_branch: str
    seed_files: list[str]

    prompt_template: ClassVar[str] = """\
{context}

You are the Semantic Triage Agent (Phase 0.5). Before the pipeline attempts a cherry-pick, \
you must analyze the commit to understand what the backport will involve.

The upstream fix diff (or stat + partial diff if too large):
<fix_diff>
{fix_diff}
</fix_diff>

Files touched by the commit:
{seed_files}

Source branch: {source_branch}
Target branch: {target_branch}

## Your Task

Analyze this commit and produce a structured assessment. For each step, use the tools available:

1. **Classify the commit**: Is this a bug fix, feature, refactor, migration, cleanup, or API change?

2. **Identify new packages**: Does the diff create any new directories/packages that don't exist on \
the target branch? Use `ls` or `git ls-tree {target_branch} -- <path>` to check.

3. **Identify new types and interfaces**: List any new struct types, interfaces, or exported functions \
introduced by the commit. For each one, check if it exists on the target branch: \
`git grep <TypeName> {target_branch} -- '*.go'`

4. **Assess dependency depth**: How many layers of new types reference each other? \
For example, if TypeA references TypeB which references TypeC, depth is 3.

5. **Identify generated and binary files**: For each file in the diff, check if it is:
   - A generated file: look for `// Code generated`, `// DO NOT EDIT`, `zz_generated.*`, \
`generated.pb.go`, `generated.proto`, `*_swagger_doc_generated.go` patterns in the file or filename
   - A binary file: `.pb` (protobuf binary), `.png`, `.jpg`, `.wasm`, or any non-text file
   List these files in `files_to_skip` — the pipeline will auto-resolve them instead of \
sending them to the LLM agent (which cannot meaningfully edit generated or binary content).

6. **Discover regeneration commands**: For each generated file, figure out how to regenerate it. Check:
   - File header comments (e.g. `// Code generated by protoc-gen-go. DO NOT EDIT.`)
   - `Makefile` targets: `grep -i -E 'generate|proto|codegen' Makefile`
   - `hack/` scripts: `ls hack/update-*` or `ls hack/*codegen*` or `ls hack/*proto*`
   - Build system files: `buf.yaml`, `build.rs`, `setup.py`, `CMakeLists.txt`
   Report the commands needed to regenerate the skipped files.

7. **Check target branch prerequisites**: For the key types/functions in the diff, do they exist on \
the target branch? Use `git grep` to verify.

8. **Trace prerequisite commits**: For each key symbol/type/import that the commit uses but doesn't \
define itself, check if it exists on the target branch. If it doesn't:
   - Find the commit that introduced it: `git log --oneline -1 -S '<SymbolName>' {source_branch} -- '*.go'`
   - Check the size of that prerequisite commit: `git show --stat <sha> | tail -1`
   - Assess whether it's a small addition (easily portable) or a large feature (its own backport problem)
   - **Important**: Also check auto-resolved files (taken from --theirs) for imports that reference \
packages not present on the target branch. These stale imports will break regeneration and must be \
identified as prerequisites.
   List the prerequisites with their introducing commits and portability assessment.

9. **Determine priority files**: Which files should the conflict resolution agent focus on first? \
These are the hand-written source files most critical to the fix's functionality. \
Exclude generated code, binary files, and test fixtures from this list.

10. **Discover verification commands**: What test commands should be run to verify the backport \
beyond the basic build+vet? Look for:
   - Roundtrip tests for API types: e.g. `go test ./staging/src/k8s.io/api/... -run TestRoundTrip`
   - Unit tests for the packages touched: e.g. `go test ./pkg/apis/scheduling/...`
   - Integration tests if they exist in the commit's scope
   These will be run in addition to the YAML-configured test command.

## Output

Write a JSON file to `{output_file}` with this exact structure:

```json
{{
  "commit_type": "bug-fix | feature | refactor | migration | cleanup | api-change",
  "new_packages": ["list of new package paths not on target"],
  "new_types_interfaces": ["list of new type/interface names"],
  "dependency_depth": 0,
  "target_has_prerequisites": true,
  "prerequisite_details": "explanation of what exists or is missing",
  "prerequisites": [
    {{
      "symbol": "name of the missing symbol/package/import",
      "introduced_by": "commit SHA that introduced it",
      "subject": "commit subject line",
      "size": "N files changed",
      "portable": true,
      "reason": "why it is or isn't easily portable"
    }}
  ],
  "generated_code_in_diff": false,
  "binary_files_in_diff": false,
  "files_to_skip": ["generated and binary files that should be auto-resolved, not sent to LLM"],
  "regeneration_commands": ["commands to regenerate the skipped files, e.g. make generate"],
  "verification_commands": ["additional test commands beyond basic build, e.g. go test ./staging/src/k8s.io/api/... -run TestRoundTrip"],
  "estimated_difficulty": "EASY | MEDIUM | HARD | EXTREME",
  "recommendation": "PROCEED | PROCEED_WITH_CAUTION | MANUAL_REVIEW",
  "priority_files": ["hand-written source files to check first during conflict resolution"],
  "reasoning": "brief explanation of the assessment"
}}
```

Difficulty guidelines:
- **EASY**: Bug fix or cleanup, no new types, all files exist on target
- **MEDIUM**: Adds a few new functions/methods to existing types, minor API differences
- **HARD**: Introduces new types/interfaces, some prerequisites missing on target, cross-package changes
- **EXTREME**: New subsystem or API group, deep dependency graph, generated code, binary files

Recommendation guidelines:
- **PROCEED**: Straightforward backport, expect clean or near-clean cherry-pick
- **PROCEED_WITH_CAUTION**: Expect conflicts and build errors requiring adaptation
- **MANUAL_REVIEW**: Very complex, human should review the result carefully
"""

    def prompt(self) -> str:
        """Render the Phase 0.5 semantic triage prompt."""
        return self.prompt_template.format(
            context=self.context,
            fix_diff=self.fix_diff,
            source_branch=self.source_branch,
            target_branch=self.target_branch,
            seed_files="\n".join(f"  - {f}" for f in self.seed_files),
            output_file=SEMANTIC_TRIAGE_FILE,
        )


@dataclass
class TestPortAgentPrompt:
    context: str
    source_fix_commit: str
    target_branch: str
    test_files: list[str]
    output_manifest_file: str

    prompt_template: ClassVar[str] = """\
{context}

You are the Test Port Agent (Phase 0.5c). Your goal is to port ONLY the test changes \
from the fix commit to the target branch. Do NOT modify any production/source code.

The fix commit {source_fix_commit} modified these test files:
{test_files}

## Rules

1. For each test file above, extract ONLY the new or modified test functions/cases from \
the fix commit. Use `git show {source_fix_commit} -- <test_file>` to see what changed.

2. Do NOT `git checkout` the entire file from the source — that would overwrite the \
target branch's version. Instead, surgically insert the new test functions into the \
existing target branch file at the correct location.

3. Do NOT modify any production code (non-test files). If a new test calls a function \
that doesn't exist yet on the target branch, that's expected — the test is meant to \
FAIL before the fix is applied (RED check). Make the test compile by adding minimal \
stubs, skip markers, or build tags if needed, but do not port the actual fix code.

4. Do NOT change existing test logic — only add new tests or update test call-sites \
to match the new function signatures from the fix.

5. After porting, run the build command to verify the test files compile.

6. Write the absolute path of every modified test file to `{output_manifest_file}`, \
one per line.
"""

    def prompt(self) -> str:
        """Render the Phase 0.5c test port prompt."""
        return self.prompt_template.format(
            context=self.context,
            source_fix_commit=self.source_fix_commit,
            target_branch=self.target_branch,
            test_files="\n".join(f"  - {f}" for f in self.test_files),
            output_manifest_file=self.output_manifest_file,
        )


TEST_PORT_MANIFEST_FILE = "test_port_manifest.txt"


@dataclass
class NarrowResolutionAgentPrompt:
    context: str
    fix_diff: str
    conflicted_files: list[str]
    allowed_modules: list[str]

    prompt_template: ClassVar[str] = """\
{context}

You are the Narrow Resolution Agent (Phase 3a). Cherry-pick produced conflicts in these files:
{conflicted_files}

The upstream fix diff for reference:
<fix_diff>
{fix_diff}
</fix_diff>

Your task is to resolve ONLY the conflict hunks (marked with <<<<<<<, =======, >>>>>>>). Constraints:

1. Resolve each conflict hunk to produce the intended fix behavior on the target branch.
2. Do NOT re-derive intent — the fix diff tells you exactly what should change.
3. Do NOT rewrite surrounding code or modify files outside the cherry-pick's scope.

## Priority files (check these first):
{allowed_modules}

You may modify any file needed to make the build and tests pass. If you need to add \
missing types, feature gates, or adapt API patterns for the target branch, do so.

After resolving all conflicts:
- Run `git diff --name-only HEAD` and verify every changed file is in the allowlist.
- If any file is outside the allowlist, undo that change and re-resolve.
- Stage and commit with the cherry-pick message plus structured trailers.
"""

    def prompt(self) -> str:
        return self.prompt_template.format(
            context=self.context,
            fix_diff=self.fix_diff,
            conflicted_files="\n".join(f"  - {f}" for f in self.conflicted_files),
            allowed_modules="\n".join(f"  - {f}" for f in self.allowed_modules),
        )


@dataclass
class BuildErrorRecoveryPrompt:
    """Prompt for Phase 4a — agent-assisted build/test error recovery."""
    context: str
    fix_diff: str
    current_diff: str
    build_errors: str
    test_errors: str
    allowed_modules: list[str]
    allowed_seed: list[str]
    target_branch: str
    build_command: str
    test_command: str
    iteration: int
    max_retries: int

    prompt_template: ClassVar[str] = """\
{context}

You are the Build Error Recovery Agent (Phase 4a, iteration {iteration}/{max_retries}).

The fix was cherry-picked from the source branch and conflicts were resolved, but the \
result does not compile or pass tests on the target branch.

The upstream fix for reference:
<fix_diff>
{fix_diff}
</fix_diff>

What was actually applied to the target branch:
<current_diff>
{current_diff}
</current_diff>

Build errors:
<build_errors>
{build_errors}
</build_errors>

Test errors:
<test_errors>
{test_errors}
</test_errors>

## What you CAN do:
- Add missing imports that exist on the target branch
- Fix function call signatures to match the target branch API (verify with `git grep`)
- Replace types/methods that don't exist on the target with their target-branch equivalents
- Remove references to symbols that don't exist and aren't required for the fix's intent
- Adapt API patterns (e.g. `tCtx.WithStep()` → `ktesting.WithStep(tCtx, ...)`)
- Add new type definitions locally if they are needed and don't exist on the target branch
- Modify any file needed to make the build and tests pass

## What you MUST NOT do:
- Change the semantic intent of the fix
- Stub out or mock missing functionality with no-op implementations

## Priority files (check these first):
{allowed_modules}

## Original seed files:
{allowed_seed}

## Process:
1. Read each error message carefully
2. For each undefined symbol: run `git grep <symbol> {target_branch}` to check if it exists
3. If it exists under a different name or signature → adapt the code
4. If it doesn't exist and is a core dependency of the fix → stop and report CANNOT_FIX
5. After fixing, run: {build_command}
6. Then run: {test_command}

If the errors require types, interfaces, or features that don't exist on the target branch \
and cannot be adapted without changing the fix's intent, write to stdout:
  CANNOT_FIX: <explanation of what's missing and why>
Do NOT attempt partial workarounds — either the fix compiles cleanly or it doesn't.
"""

    def prompt(self) -> str:
        """Render the Phase 4a recovery prompt with all context sections."""
        return self.prompt_template.format(
            context=self.context,
            fix_diff=self.fix_diff,
            current_diff=self.current_diff,
            build_errors=self.build_errors,
            test_errors=self.test_errors,
            allowed_modules="\n".join(f"  - {f}" for f in self.allowed_modules),
            allowed_seed="\n".join(f"  - {f}" for f in self.allowed_seed),
            target_branch=self.target_branch,
            build_command=self.build_command,
            test_command=self.test_command,
            iteration=self.iteration,
            max_retries=self.max_retries,
        )


